Repository chiewyx/hawkerDream, pull requests merged in 2022-06, with the labels that each got.

#27 updated invoice page
  src/components/invoiceCard.js
  src/pages/dashboard.js
  src/pages/months/april.js
  src/pages/months/august.js
  src/pages/months/december.js
  src/pages/months/february.js
  src/pages/months/january.js
  src/pages/months/july.js
  src/pages/months/june.js
  src/pages/months/march.js
  src/pages/months/may.js
  src/pages/months/november.js
  src/pages/months/october.js
  src/pages/months/september.js
  src/pages/newInvoice.js
Labels: high

#28 Order
  src/components/orderCard.js
  src/index.css
  src/pages/addOrder.js
  src/pages/newInvoice.js
  src/pages/newOrder.js
  src/pages/order.js
Labels: high

#29 update add order page
  src/pages/addOrder.js
Labels: bug

#30 included the price in order list
  src/components/orderCard.js
  src/pages/marketplace.js
  src/pages/newOrder.js
Labels: medium

#34 mark orders as completed
  src/components/orderCard.js
  src/pages/addOrder.js
  src/pages/order.js
Labels: high

#35 invoices - allow users to download their upload invoices
  src/components/invoiceCard.js
  src/components/monthCard.js
Labels: high, medium

#36 marketplace - order
  src/components/mktOrder.js
  src/components/productCard.js
  src/pages/marketplace.js
Labels: high

#38 added RequireAuth so users cannot access dashboard if not authenticated
  src/components/privateRoute.js
  src/pages/App.js
Labels: bug
