Repository chiewyx/hawkerDream, pull requests merged in 2022-07, with the labels that each got.

#44 Order
  package-lock.json
  package.json
  src/components/mktOrder.js
  src/components/orderCard.js
  src/pages/addOrder.js
  src/pages/dashboard.js
  src/pages/marketplace.js
  src/pages/newOrder.js
  src/pages/update.js
Labels: high

#46 fixed bugs
  src/pages/months/april.js
  src/pages/months/august.js
  src/pages/months/december.js
  src/pages/months/february.js
  src/pages/months/january.js
  src/pages/months/july.js
  src/pages/months/march.js
  src/pages/months/may.js
  src/pages/months/november.js
  src/pages/months/october.js
  src/pages/months/september.js
Labels: bug

#47 included alert dialog
  src/components/orderCard.js
Labels: enhancement

#50 allow hawkers to view orders
  src/components/mktOrder.js
  src/components/orderCard.js
  src/pages/addOrder.js
Labels: high

#51 added widgets for dashboard page
  src/pages/dashboard.js
Labels: medium

#55 added a completed orders page
  src/pages/App.js
  src/pages/completedOrder.js
  src/pages/dashboard.js
Labels: enhancement

#57 validated order form for marketplace
  src/components/mktOrder.js
Labels: enhancement

#59 linked completed orders page with orders
  src/pages/completedOrder.js
  src/pages/order.js
Labels: enhancement

#61 improved the order list for users
  src/components/mktOrder.js
  src/pages/newOrder.js
Labels: enhancement

#64 updated units to show at order form
  src/pages/addOrder.js
Labels: bug

#66 Invoice - can calculate total invoice cost of the month
  src/components/mktOrder.js
  src/components/orderCard.js
  src/pages/dashboard.js
Labels: enhancement

#71 organised the code
  src/components/invoiceCard.js
  src/components/monthCard.js
  src/components/navbar.js
  src/components/orderCard.js
  src/components/productCard.js
  src/components/profilebar.js
  src/components/uploadImg.js
  src/components/yearCard.js
  src/pages/App.js
  src/pages/features.js
  src/pages/featuresupplier.js
  src/pages/invoice.js
  src/pages/invoiceSystem/month.js
  src/pages/invoiceSystem/newInvoice.js
  src/pages/invoiceSystem/year.js
  src/pages/landingPages/landing.js
  src/pages/landingPages/login.js
  src/pages/landingPages/signup.js
  src/pages/marketplace.js
  src/pages/months/april.js
  src/pages/months/august.js
  src/pages/months/december.js
  src/pages/months/february.js
  src/pages/months/january.js
  src/pages/months/july.js
  src/pages/months/june.js
  src/pages/months/march.js
  src/pages/months/may.js
  src/pages/months/november.js
  src/pages/months/october.js
  src/pages/months/september.js
  src/pages/orderSystem/addOrder.js
  src/pages/orderSystem/completedOrder.js
  src/pages/orderSystem/newOrder.js
  src/pages/orderSystem/order.js
  src/pages/usersPages/dashboard.js
  src/pages/usersPages/update.js
Labels: enhancement

#72 Testing
  package-lock.json
  package.json
  src/pages/landingPages/login.js
  src/pages/landingPages/login.test.js
  src/pages/landingPages/signup.js
  src/pages/landingPages/signup.test.js
  src/pages/usersPages/dashboard.js
  src/pages/usersPages/dashboard.test.js
Labels: testing

#74 improved ui/ux
  src/components/mktOrder.js
  src/components/orderCard.js
  src/components/profilebar.js
  src/pages/orderSystem/addOrder.js
  src/pages/orderSystem/completedOrder.js
  src/pages/orderSystem/order.js
  src/pages/usersPages/update.js
Labels: enhancement

#76 added invoice test
  src/pages/invoiceSystem/newInvoice.test.js
Labels: testing
